FROM elasticsearch

MAINTAINER vickrame

RUN cd /usr/share/elasticsearch; bin/plugin install mobz/elasticsearch-head; bin/plugin install lmenezes/elasticsearch-kopf/2.0/v2.1.1; bin/plugin install royrusso/elasticsearch-HQ;