serveur-eureka:
  image: serveur/eureka
  expose:
    - "8761"
  ports:
    - "8761:8761"
  volumes:
    - ./var/logs/:/var/logs/
elasticsearch:
  image: vickrame-elastic
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - ./elasticsearch/data:/usr/share/elasticsearch/data
#    - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
serveur-zuul:
  image: serveur/zuul
  expose:
    - "8762"
  ports:
    - "8762:8762"
  volumes:
    - ./var/logs/:/var/logs/
  links:
   - serveur-eureka:annuaire
annuaire-Personne:
  image: annuaire/personne
  expose:
    - "8061"
  ports:
    - "8061:8061"
  volumes:
    - ./var/logs/:/var/logs/
  links:
   - serveur-eureka:annuaire
   - elasticsearch:es
annuaire-Taxi:
  image: annuaire/taxi
  expose:
    - "8062"
  ports:
    - "8062:8062"
  volumes:
    - ./var/logs/:/var/logs/
  links:
   - serveur-eureka:annuaire
   - elasticsearch:es
serveur-hystrix:
  image: serveur/hystrix
  expose:
    - "8763"
  ports:
    - "8763:8763"
  volumes:
    - ./var/logs/:/var/logs/
  links:
   - serveur-eureka:annuaire
kibana:
  image: kibana
  expose:
    - "5601"
  links:
    - elasticsearch:elasticsearch
  ports:
    - "5601:5601"
logstash:
  image: logstash
  expose:
    - "12201"
  ports:
    - "12201:12201"
    - "12201:12201/udp"
  volumes:
    - ./logstash/conf/:/conf/
    - ./logstash/pattern/:/pattern/
    - ./var/logs/:/var/logs/
#    - ./logstatsh/conf/:/conf/
#    - ./logstatsh/pattern/grok-patterns:/pattern/grok-patterns
#    - ./logstatsh/pattern/java:/pattern/java
#    - ./logstatsh/pattern/prez-elk:/pattern/prez-elk
  links:
    - elasticsearch:es
#    - rabbitmq:rabbitmq
  command: logstash -f /conf/conf-logstash.conf
#  command: ls -l /conf
  environment:
    - LS_JAVA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=18080 -Dcom.sun.management.jmxremote.rmi.port=18080 -Djava.rmi.server.hostname=DOCKER_HOST_IP -Dcom.sun.management.jmxremote.local.only=false
